#mySql
library(DBI)
library(RODBC)
library(odbc)
con<-odbcConnect("MySql")
sqlQuery(con,'select *from  employee')
sqlQuery(con,'select *from  department')

#project
sqlQuery(con,'SELECT ENO, NAME FROM EMPLOYEE')

#3.CARTESIAN PRODUCT
sqlQuery(con,'SELECT *FROM EMPLOYEE CROSS JOIN DEPARTMENT;')


#EQUI JOIN
sqlQuery(con,'SELECT EMPLOYEE.ENO,EMPLOYEE.NAME,EMPLOYEE.DNO,DEPARTMENT.DNMAE
FROM 
  EMPLOYEE
JOIN 
  DEPARTMENT ON EMPLOYEE.DNO = DEPARTMENT.DNO')

#left outer join
sqlQuery(con,
'SELECT 
EMPLOYEE.ENO,
EMPLOYEE.NAME,
EMPLOYEE.DNO,
DEPARTMENT.DNO,
DEPARTMENT.DNMAE
FROM 
EMPLOYEE
LEFT OUTER JOIN 
DEPARTMENT ON EMPLOYEE.DNO = DEPARTMENT.DNO')

#Right outer Join
sqlQuery(con,
'SELECT 
EMPLOYEE.ENO,
EMPLOYEE.NAME,
EMPLOYEE.DNO,
DEPARTMENT.DNO,
DEPARTMENT.DNMAE
FROM 
EMPLOYEE
RIGHT OUTER JOIN 
DEPARTMENT ON EMPLOYEE.DNO = DEPARTMENT.DNO')


